const ptBR = {
	login: 'Área de Login',
	email: 'E-mail',
	register: 'Registrar',
	username: 'Nome do Usuário',
	password: 'Senha',
	next: 'Avançar',
	fieldempty: 'Este campo não pode ficar vazio',
	email_already_registered: 'E-mail já cadastrado',
	unexpected_error: 'Ocorreu um erro inesperado',
	user_not_found: 'Usuário não encontrado',
	password_error: 'Senha invalida',
	logo: 'Money Store',
	help: 'Ajuda',
	tradearea: 'Área de Troca',
	view_more: 'Exibir Mais',
	your_wallet: 'Sua Carteira',
	money_avaible: 'Dinheiro Disponível',
	your_coins: 'Suas Moedas',
	total_invested: 'Total Investido',
	latest_operations: 'Últimas operações',
	see_complete_extract: 'Ver Extrato Completo',
	buy: 'Comprar',
	sell: 'Vender',
	value_in_reais: 'Valor em Reais',
	title: 'Título',
	total: 'Total',
	unit: 'Unidades',
	select_quantity_you_want_buy: 'Selecione a quantidade que deseja comprar',
	how_much_you_want_buy: 'Quanto deseja comprars?',
	coin: 'Moeda',
	atention_buy:
		'Atenção, ao clicar em comprar você esta confirmando a compra desta quantia em moedas',
	field_require_number: 'Você deve informar um número maior que 0',
	price: 'Preço',
	invalid_money: 'Você não tem este dinheiro para a compra',
	invalid_quote: 'Sua moeda recebeu outra cotação',
	invalid_quantity_very_short:
		'Para finalizar a operação é necessario que o total seja maior que R$ 1,00',
};

const enUS = {
	login: 'Login',
	email: 'E-mail',
	register: 'Register',
	username: 'Username',
	password: 'Password',
	next: 'Next',
	fieldempty: 'This field cannot be empty',
	email_already_registered: 'E-mail already registered',
	unexpected_error: 'An unexpected error has occurred',
	user_not_found: 'User not found',
	password_error: 'Invalid Password',
	logo: 'Money Store',
	help: 'Help',
	myaccount: 'My Account',
	tradearea: 'Trade Area',
	view_more: 'View More',
	your_wallet: 'Your Wallet',
	money_avaible: 'Money Avaible',
	your_coins: 'Your Coins',
	total_invested: 'Total Invested',
	latest_operations: 'Latest operations',
	see_complete_extract: 'See Complete Extract',
	buy: 'Buy',
	sell: 'Sell',
	value_in_reais: 'Value in Reais',
	title: 'Title',
	total: 'Total',
	unit: 'Unit',
	select_quantity_you_want_buy: 'Select the quantity you want to buy',
	how_much_you_want_buy: 'How much do you want to buy?',
	coin: 'Coin',
	atention_buy:
		'Attention, by clicking on buy you are confirming the purchase of this amount in coins',
	field_require_number: 'You must enter a number greater than 0',
	price: 'Price',
	invalid_money: 'You do not have that money to buy',
	invalid_quote: 'Your currency received another quote',
	invalid_quantity_very_short:
		'To complete the operation, the total must be greater than R$ 1,00',
};

const lang = navigator.language === 'pt-BR' ? ptBR : enUS;

export default { ...lang };
